name: CI build and checks

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:

      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run cargo build
        run: cargo build --verbose

      - name: Run cargo clippy
        run: cargo clippy --all

      - name: Run cargo fmt
        run: cargo fmt --all

      - name: Run documentation
        run: cargo doc --no-deps --package smart-clone