name: Code coverage

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        run: cargo tarpaulin --packages smart-clone-internals --out Xml --verbose

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true