name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run all tests
        run: cargo test --workspace --all-features --verbose --color=always
        env:
          RUST_BACKTRACE: 1